### ISSUE TITLE
Wrapper for Swift

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [sbooth/CXXTagLib#1]
Hey @sbooth, thanks for mentioning this repo! I'm already testing it!

Initially, I found your repo https://github.com/sbooth/SFBAudioEngine, which seems to have completed wrappers for Swift. I'm looking for a library that can read and ideally edit metadata for MP3, MP4, and FLAC files.

So, using this repo([CXXTagLib]) in Swift classes requires an additional wrapper, as I understand it?

**Comment by Anywhere-Music-Player** [comment]
Also, another question is - how to sync with official TagLib repo changes in this repo if they release new version? I mean just manually replace update files..?

**Comment by sbooth** [comment]
Unless you're using Swift's C++ compatibility you will need a wrapper.

The update is a manual process for new TagLib versions.
